### ISSUE TITLE
update links

### ISSUE THREAD

**Issue by y-nk** [kasir-barati/you-say#3]
i'm super sorry to ask you this here, but i found your conversation about nestjs config providing links to this repo in order to showcase config partial registration with class-validator as validation schema. the links are outdated, but i'd still be interested in seeing them. could you let me know where are those files now?

https://github.com/nestjs/config/issues/209#issuecomment-1059695343

**Comment by kasir-barati** [comment]
@y-nk yes, here is how I love to do it:
1. https://github.com/kasir-barati/you-say/blob/main/apps/backend/src/modules/keycloak/configs/keycloak.config.ts
2. https://github.com/kasir-barati/you-say/blob/main/apps/backend/src/modules/keycloak/configs/keycloak-connect-module.config.ts

**Comment by y-nk** [comment]
thanks for the quick answer @kasir-barati 🙏
